### ISSUE TITLE
Is lib folder forked from ffjord repo?

### ISSUE THREAD

**Issue by juntang-zhuang** [KrishnaswamyLab/TrajectoryNet#1]
Hi, thanks for providing the code. Just a quick question, when I skim over the code, I wonder if the folder /TrajectoryNet/lib is forked from the ffjord repo? Which file is modified? Just a quick question so I can focus on the different part of your paper.

**Comment by atong01** [comment]
Yes, you are correct the lib folder is forked from ffjord. I believe the only modifications in that folder are in the visualization files `viz_scrna.py` and `visualize_flow.py` and `growth_net.py`.

**Comment by juntang-zhuang** [comment]
Thanks for the reply
