### ISSUE TITLE
loss function energy regularization term

### ISSUE THREAD

**Issue by BeatriceCai** [KrishnaswamyLab/TrajectoryNet#16]
Hi, 

It's such a wonderful work. I have been reading the paper and trying to find each corresponding piece of code.  Could you point out which lines of code is the L_energy term in the loss function?

Thanks

**Comment by atong01** [comment]
Hi,

The lines for the `L_energy` term in the paper are correspond to `--sl2int` and `--JFrobint` in the parameters file.

**Comment by BeatriceCai** [comment]
Thanks for the update! Tian Cai PhD Candidate in Computer Science The Graduate Center, CUNY From: Alexander TongSent: Wednesday, February 9, 2022 12:05 AMTo: KrishnaswamyLab/TrajectoryNetCc: Tian Cai; AuthorSubject: Re: [KrishnaswamyLab/TrajectoryNet] loss function energy regularization term (Issue #16) Hi,The lines for the L_energy term in the paper are correspond to --sl2int and --JFrobint in the parameters file.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
