### ISSUE TITLE
Make TrajectoryNet pip installable

### ISSUE THREAD

**Issue by MUCDK** [KrishnaswamyLab/TrajectoryNet#17]
Hey,

Thanks a lot for your great repo!

Would it be possible to make TrajectoryNet pip-dev-installable? E.g. in main.py instead of 
```from lib.growth_net import GrowthNet```
do 
```from TrajectoryNet.lib.growth_net import GrowthNet```
so we can use it in an environment?

Thank you very much!

**Comment by atong01** [comment]
Hi!

This is probably worth doing. I'll put it on the todo list and ping you here when its done. If you already have the changes for this somewhere would welcome a PR.

Thanks,
Alex

**Comment by atong01** [comment]
TrajectoryNet should be pip installable as of 0.2.4 (and on pypi). closing the issue.
