### ISSUE TITLE
UnboundLocalError: local variable 'growth_model_path' referenced before assignment

### ISSUE THREAD

**Issue by dadashkarimi** [KrishnaswamyLab/TrajectoryNet#2]
Hi,
For some reason I keep getting this error. Do I need to pass an argument?
-Javid

**Comment by lashoun** [comment]
Just confirming that I have the same error.

**Comment by atong01** [comment]
Sorry about that, should be fixed now. I'm planning on improving this code in the near future as this is very much the code I used for experimentation.
