### ISSUE TITLE
Couldn´t open that Evaluation Notebook

### ISSUE THREAD

**Issue by Holmes815** [KrishnaswamyLab/TrajectoryNet#22]
Hi

I can´t open the evaluation notebook (https://github.com/KrishnaswamyLab/TrajectoryNet/blob/master/notebooks/EB-Eval.ipynb) linked in the Embryoid Body Trajectory Inference notebook

Thank you for your attention

**Comment by atong01** [comment]
Yes, we removed this as the new one is nicer. It can be found in an earlier commit here if you're interested: 
https://github.com/KrishnaswamyLab/TrajectoryNet/blob/0b50a32262c94bb437b73533bd7b4f670d20b444/notebooks/EB-Eval.ipynb

**Comment by Holmes815** [comment]
Thank you for the quick response! This issue is now solved *wooosh
