### ISSUE TITLE
Execution Error for Running with Dataset SCURVE and EB

### ISSUE THREAD

**Issue by Zacharyyhk** [KrishnaswamyLab/TrajectoryNet#25]
By running either one of the following two commands for dataset SCURVE and EB:
python -m TrajectoryNet.main --dataset SCURVE
or
python -m TrajectoryNet.main, 

the following error is given:
"AssertionError: If using tupled rtol it must have the same length as the tuple yo"
in "'～/TrajectoryNet/main.py', line 269, in train 
loss.backward()"

**Comment by Zacharyyhk** [comment]
For detailed trackback:
![TrajectoryNet_RunningError](https://github.com/user-attachments/assets/1149a255-1671-441e-b93e-66f783ad1597)

**Comment by atong01** [comment]
Which torchdiffeq version do you have? TrajectoryNet only works with the specified (really early) version.

**Comment by Zacharyyhk** [comment]
Thanks for your prompt reply!

The version of torchdiffeq is 0.2.4  which is matched with the number specified in "TrajectoryNet/version.py" and the version of torchdiffeqpack is 1.0.1.

**Comment by atong01** [comment]
Gotcha, yep. This is the problem. You need version `torchdiffeq==0.0.1` see requirements.txt here:
https://github.com/KrishnaswamyLab/TrajectoryNet/blob/master/requirements.txt

Although I haven't tried these in a while. This is the only annoying requirement that I can remember.

**Comment by Zacharyyhk** [comment]
Thank you!
I will try running the code with torchdiffeq==0.0.1.
