### ISSUE TITLE
Gif Creation and a few other questions

### ISSUE THREAD

**Issue by lashoun** [KrishnaswamyLab/TrajectoryNet#3]
How did you create the .gif you showcase in the README? I tried grepping the repo for ".gif" but I did not find anything.
I have run the command you suggest and it produces a result folder with a `figs` folder that contains pictures of the timestamps if I understood correctly, a file `checkpt.pth`, a file `logs`, a file `train_eval.csv` and a file `vectors.jpg`.
Also, when running `python main.py --dataset="EB" --niters=100`, the `figs` pictures look nothing like your gif. Is that normal? I do not see why the starting and ending points aren't the same since the algorithm is supposed to perform optimal transport.
Furthermore, I fail to see the relationship between the `figs` pictures and `vectors.jpg`: could you please explain briefly?
Thank you for your attention.

**Comment by atong01** [comment]
Hi lashoun,

This gif was created via mp4. The code is meant to produce mp4s, for websites I used a standard mp4 --> gif converter. You should find usage in line 409 of `main.py`. `trajectory_save_density` creates a bunch of jpegs which are then stitched together into an mp4. There are many different ways to visualize the data. the code is based on a PCA embedding of the data, the gif is TrajectoryNet trained on a 2d PHATE embedding of the cells. This is not invertible, but is preferable for visualization.

The vectors.jpg is supposed to show the passage of specific points over time. it samples points at the end timepoint then integrates their location backwards in time. The `figs` pictures are meant to show the density over time over training.

Hope this helps! Let me know if you have any other quesitions,
--Alex

**Comment by lashoun** [comment]
Thank you for the answer, I understand the results better now! I also found out the root cause of my problem: the `return` statement on line 395 of `main.py`, [here](https://github.com/KrishnaswamyLab/TrajectoryNet/blob/master/TrajectoryNet/main.py#L395). Commenting it enabled me to generate the videos. Therefore, I'm closing the issue.
