### ISSUE TITLE
Some questions about the data formatting and usage

### ISSUE THREAD

**Issue by sushantbangru** [KrishnaswamyLab/TrajectoryNet#4]
Hello,

This is very interesting and cool work. I am looking to use this on my timepoint scRNAseq dataset, and follow up after running phate. But, I am unclear on what kind of data the different data structures the .npz file contain. Since, I have run most of existing analysis in R, I am unclear on what all data needs to be used to make the npz file...

I mean these structures ... 

['pcs', 'phate', 'delta_embedding', 'color', 'ixs', 'sample_labels', 'pcs_delta']

P.S. Is there an existing vignette/tutorial for using Trajectory Net. 

Thank you.

**Comment by atong01** [comment]
Hi Sushant,

I've just added some examples of how to load data in the `/notebooks` folder. Please let me know if this clears it up for you.

**Comment by sushantbangru** [comment]
This is really helpful. Thanks a lot.
