### ISSUE TITLE
Getting Assertion error using custom dataset

### ISSUE THREAD

**Issue by sushantbangru** [KrishnaswamyLab/TrajectoryNet#6]
Used the following command:
`python main.py --dataset hep_fmnn.npz --embedding_name phate`

Getting the following error;

`Traceback (most recent call last):
  File "main.py", line 506, in <module>
    main(args)
  File "main.py", line 441, in main
    args.data = dataset.SCData.factory(args.dataset, args)
  File "/TrajectoryNet-master/TrajectoryNet/dataset.py", line 190, in factory
    return CustomData(name, args)
  File "/TrajectoryNet-master/TrajectoryNet/dataset.py", line 198, in __init__
    self.load(name, args.max_dim)
  File "/TrajectoryNet-master/TrajectoryNet/dataset.py", line 209, in load
    assert self.labels.shape[0] == self.ncells
AssertionError`

**Comment by atong01** [comment]
Hi, this last line
```
master/TrajectoryNet/dataset.py", line 209, in load assert self.labels.shape[0] == self.ncells AssertionError
```

Means that the shape of your label array is not the same as the number of cells. You should check that the data you are supplying matches the specification i.e. you have

1. An embedding matrix titled [embedding_name] (Cells x Dimensions)
2. A sample labels array titled sample_labels (Cells)

This assertion tests that these two arrays have the same first dimension.

**Comment by sushantbangru** [comment]
That seemed to solve the problem. Thanks for the help.
